# Three-Tier Architecture Application Configuration
spring:
  application:
    name: three-tier-architecture
  datasource:
    url: jdbc:h2:mem:threetierdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080