# Four-Tier Architecture Application Configuration
spring:
  application:
    name: four-tier-architecture
  datasource:
    url: jdbc:h2:mem:fourtierdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  # MyBatis Configuration
  mybatis:
    mapper-locations: classpath:mappers/**/*.xml
    type-aliases-package: com.example.fourtier.infrastructure.persistence.entity
    configuration:
      map-underscore-to-camel-case: true
  # Thymeleaf Configuration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    enable-spring-el-compiler: true

server:
  port: 8081

# Logging Configuration
logging:
  level:
    root: INFO
    com.example.fourtier: DEBUG
